name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Läuft alle 12 Stunden (Automatische Ausführung)
  workflow_dispatch:  # Manuelle Auslösung auch weiterhin möglich

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: itsmarianmc
          bg_color: "#1e1e1e"
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push generated snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
